export const agencyGoalsHeader = [
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
];
export const otherActivitiesHeader = [
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
	{value:'Goals', type:true},
	{value:'Actual', type:false},
];

export const autoAndFireHeader = [
	{ id: 1, value: 'Personally Produced', type: true, color: 'bg-yellow-500' },
	{ id: 2, value: 'Raw New', type: true, color: 'bg-yellow-500' },
	{ id: 3, value: 'Add On', type: true, color: 'bg-yellow-500' },
	{ id: 4, value: 'Transfer In', type: true, color: 'bg-yellow-500' },
	{ id: 5, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 6, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 7, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 8, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 9, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 10, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 11, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 12, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 13, value: 'Total Auto', type: true, color: 'bg-yellow-500' },
	{ id: 14, value: 'Personally Produced', type: true, color: 'bg-green-300' },
	{ id: 15, value: 'Raw New', type: true, color: 'bg-green-300' },
	{ id: 16, value: 'Add On', type: true, color: 'bg-green-300' },
	{ id: 17, value: 'Transfer In', type: true, color: 'bg-green-300' },
	{ id: 18, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 19, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 20, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 21, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 22, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 23, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 24, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 25, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 26, value: 'TotalFire', type: true, color: 'bg-green-300' },
];

export const lifeAndHealthHeader = [
	{ id: 1, value: 'Term', type: true, color: 'bg-yellow-500' },
	{ id: 2, value: 'Whole Life', type: true, color: 'bg-yellow-500' },
	{ id: 3, value: 'Universal Life', type: true, color: 'bg-yellow-500' },
	{ id: 4, value: 'UL Bump', type: true, color: 'bg-yellow-500' },
	{ id: 5, value: 'Limited Pay', type: true, color: 'bg-yellow-500' },
	{ id: 6, value: 'Final Expense', type: true, color: 'bg-yellow-500' },
	{ id: 7, value: 'Single Premium', type: true, color: 'bg-yellow-500' },
	{ id: 8, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 9, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 10, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 11, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 12, value: 'Annuity', type: true, color: 'bg-yellow-500' },
	{ id: 13, value: 'TotalLife', type: true, color: 'bg-yellow-500' },
	{ id: 14, value: 'Short-Term Disability', type: true, color: 'bg-green-300' },
	{ id: 15, value: 'Long-Term Disability', type: true, color: 'bg-green-300' },
	{ id: 16, value: 'Hospital Income', type: true, color: 'bg-green-300' },
	{ id: 17, value: 'ICDI', type: true, color: 'bg-green-300' },
	{ id: 18, value: 'Med Sup', type: true, color: 'bg-green-300' },
	{ id: 19, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 20, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 21, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 22, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 23, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 24, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 25, value: 'label', type: true, color: 'bg-green-300' },
	{ id: 26, value: 'Total Health', type: true, color: 'bg-green-300' },
	{ id: 27, value: 'Total Policies', type: true, color: 'bg-green-300' },
];

export const bankHeader = [
	{ id: 1, value: 'Producer', type: true, color: 'bg-yellow-500' },
	{ id: 2, value: 'Label', type: true, color: 'bg-yellow-500' },
	{ id: 3, value: 'Label', type: true, color: 'bg-yellow-500' },
	{ id: 4, value: 'Label', type: true, color: 'bg-yellow-500' },
	{ id: 5, value: 'Label', type: true, color: 'bg-yellow-500' },
	{ id: 6, value: 'Label', type: true, color: 'bg-yellow-500' },
	{ id: 7, value: 'Label', type: true, color: 'bg-yellow-500' },
	{ id: 8, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 9, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 10, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 11, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 12, value: 'Label', type: true, color: 'bg-yellow-500' },
	{ id: 13, value: 'Label', type: true, color: 'bg-yellow-500' },
	{ id: 14, value: 'Label', type: true, color: 'bg-yellow-500' },
	{ id: 15, value: 'Total', type: true, color: 'bg-yellow-500' },
];

export const StaffSources_Header = [
	{ id: 4, value: 'Center of Influence', type: true, color: '' },
	{ id: 5, value: 'Client Request', type: true, color: '' },
	{ id: 6, value: 'Direct Mail Letter', type: true, color: '' },
	{ id: 7, value: 'Internet Read >>', type: true, color: '' },
	{ id: 8, value: 'Multiline Review', type: true, color: '' },
	{ id: 9, value: 'Networking Meeting', type: true, color: '' },
	{ id: 10, value: 'Call In', type: true, color: '' },
	{ id: 11, value: 'Outbound Calling', type: true, color: '' },
	{ id: 12, value: 'Personal Visit', type: true, color: '' },
	{ id: 13, value: 'Postcard', type: true, color: '' },
	{ id: 14, value: 'Referral', type: true, color: '' },
	{ id: 15, value: 'Salesperson Pilvot', type: true, color: '' },
	{ id: 16, value: 'Sign', type: true, color: '' },
	{ id: 17, value: 'Television', type: true, color: '' },
	{ id: 18, value: 'Transfer', type: true, color: '' },
	{ id: 19, value: 'Walk-In', type: true, color: '' },
	{ id: 20, value: 'Website', type: true, color: '' },
	{ id: 21, value: 'WebSearch', type: true, color: '' },
	{ id: 22, value: 'Yellow Pages', type: true, color: '' },
	{ id: 23, value: 'Other', type: true, color: '' },
	{ id: 24, value: 'Total', type: true, color: '' },
];

export const ViewGrid_Header = [
	{ id: 1, value: 'Sources', type: true, color: '' },
	{ id: 2, value: 'Auto', type: true, color: '' },
	{ id: 3, value: 'Fire', type: true, color: '' },
	{ id: 4, value: 'Life', type: true, color: '' },
	{ id: 5, value: 'Health', type: true, color: '' },
	{ id: 6, value: 'Bank', type: true, color: '' },
	{ id: 7, value: 'Total', type: true, color: '' },
];

export const Producer_StaffMultiline_Ratios_Table = [
	{ id: 1, value: 'Policies', type: true, color: '' },
	{ id: 2, value: 'Annual Premium', type: true, color: '' },
	{ id: 3, value: 'Average Prenium', type: true, color: '' },
	{ id: 4, value: 'Auto Bonus', type: true, color: '' },
	{ id: 5, value: 'Policies', type: true, color: '' },
	{ id: 6, value: 'Annual Premium', type: true, color: '' },
	{ id: 7, value: 'Average Prenium', type: true, color: '' },
	{ id: 8, value: 'Auto Bonus', type: true, color: '' },
	{ id: 9, value: 'Policies', type: true, color: '' },
	{ id: 10, value: 'Annual Premium', type: true, color: '' },
	{ id: 11, value: 'Average Prenium', type: true, color: '' },
	{ id: 12, value: 'Auto Bonus', type: true, color: '' },
	{ id: 13, value: 'Policies', type: true, color: '' },
	{ id: 14, value: 'Annual Premium', type: true, color: '' },
	{ id: 15, value: 'Average Prenium', type: true, color: '' },
	{ id: 16, value: 'Auto Bonus', type: true, color: '' },
	{ id: 17, value: 'Policies', type: true, color: '' },
	{ id: 18, value: 'Annual Premium', type: true, color: '' },
	{ id: 19, value: 'Average Prenium', type: true, color: '' },
	{ id: 20, value: 'Auto Bonus', type: true, color: '' },
	{ id: 21, value: 'Policies', type: true, color: '' },
	{ id: 22, value: 'Annual Premium', type: true, color: '' },
	{ id: 23, value: 'Average Prenium', type: true, color: '' },
	{ id: 24, value: 'Auto Bonus', type: true, color: '' },
	{ id: 24, value: 'Multiline Ratio', type: true, color: '' },
];

export const Producer_StaffMultiline_Summary_Table = [
	{ id: 1, value: 'Fire', type: true, color: '' },
	{ id: 2, value: 'Life', type: true, color: '' },
	{ id: 3, value: 'Health', type: true, color: '' },
	{ id: 4, value: 'Bank', type: true, color: '' },
	{ id: 5, value: 'Fire', type: true, color: '' },
	{ id: 6, value: 'Life', type: true, color: '' },
	{ id: 7, value: 'Health', type: true, color: '' },
	{ id: 8, value: 'Bank', type: true, color: '' },
	{ id: 9, value: 'Fire', type: true, color: '' },
	{ id: 10, value: 'Life', type: true, color: '' },
	{ id: 11, value: 'Health', type: true, color: '' },
	{ id: 12, value: 'Bank', type: true, color: '' },
	{ id: 13, value: 'Fire', type: true, color: '' },
	{ id: 14, value: 'Life', type: true, color: '' },
	{ id: 15, value: 'Health', type: true, color: '' },
	{ id: 16, value: 'Bank', type: true, color: '' },
	{ id: 17, value: 'Fire', type: true, color: '' },
	{ id: 18, value: 'Life', type: true, color: '' },
	{ id: 19, value: 'Health', type: true, color: '' },
	{ id: 20, value: 'Bank', type: true, color: '' },
	{ id: 21, value: 'Life', type: true, color: '' },
	{ id: 22, value: 'Health', type: true, color: '' },
	{ id: 23, value: 'Bank', type: true, color: '' },
	{ id: 24, value: 'Total L/H/B', type: true, color: '' },
	{ id: 25, value: 'Auto', type: true, color: '' },
	{ id: 26, value: 'Fire', type: true, color: '' },
	{ id: 27, value: 'Life', type: true, color: '' },
	{ id: 28, value: 'Health', type: true, color: '' },
	{ id: 29, value: 'Bank', type: true, color: '' },
];
